# Generated by Django 5.2.8 on 2025-12-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_address_line1_client_address_line2_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["deadline"], name="projects_pr_deadlin_bd2912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["client", "status"], name="projects_pr_client__60b095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["client", "deadline"], name="projects_pr_client__72dec6_idx"
            ),
        ),
    ]
