# Generated by Django 5.2.8 on 2025-12-15 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_client_address_line1_client_address_line2_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("image", "Génération d'images"),
                            ("video", "Génération de vidéos"),
                            ("audio", "Génération audio"),
                            ("both", "Images & Vidéos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("monthly", "Abonnement mensuel"),
                            ("credits", "Basé sur crédits"),
                            ("per_use", "Par utilisation"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "default_monthly_cost_mad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût mensuel par défaut en MAD",
                        max_digits=10,
                    ),
                ),
                (
                    "default_credits_per_month",
                    models.IntegerField(
                        default=0, help_text="Crédits par défaut inclus par mois"
                    ),
                ),
                (
                    "default_cost_per_image_mad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût par image en MAD",
                        max_digits=10,
                    ),
                ),
                (
                    "default_cost_per_video_second_mad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût par seconde de vidéo en MAD",
                        max_digits=10,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Outil IA",
                "verbose_name_plural": "Outils IA",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_month",
                    models.DateField(help_text="Premier jour du mois de facturation"),
                ),
                (
                    "total_cost_mad",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total payé en MAD",
                        max_digits=10,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "original_currency",
                    models.CharField(
                        default="MAD", help_text="USD, EUR, ou MAD", max_length=3
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Taux de change vers MAD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_credits",
                    models.IntegerField(
                        blank=True, help_text="Crédits totaux inclus", null=True
                    ),
                ),
                ("credits_remaining", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="subscriptions.aitool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-billing_month"],
                "unique_together": {("tool", "billing_month")},
            },
        ),
        migrations.CreateModel(
            name="CreditUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("audio", "Audio"),
                            ("other", "Autre"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("credits_used", models.IntegerField(default=0)),
                ("items_generated", models.IntegerField(default=1)),
                (
                    "video_seconds",
                    models.IntegerField(
                        default=0, help_text="Durée en secondes (pour vidéos)"
                    ),
                ),
                (
                    "calculated_cost_mad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "manual_cost_mad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coût manuel en MAD (override le calcul automatique)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("usage_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_usages",
                        to="clients.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_usages",
                        to="projects.project",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation",
                "verbose_name_plural": "Utilisations",
                "ordering": ["-usage_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientServiceSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_selections",
                        to="clients.client",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_selections",
                        to="subscriptions.aitool",
                    ),
                ),
            ],
            options={
                "ordering": ["tool__display_name"],
                "unique_together": {("client", "tool")},
            },
        ),
    ]
