# Generated by Django 5.2.8 on 2025-12-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="free_credits_per_month",
            field=models.IntegerField(default=0, help_text="Crédits gratuits par mois"),
        ),
        migrations.AddField(
            model_name="aitool",
            name="free_features",
            field=models.TextField(
                blank=True,
                help_text="Caractéristiques du plan Free (séparées par virgule)",
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="free_monthly_cost_mad",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Coût mensuel Free (généralement 0)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="premier_credits_per_month",
            field=models.IntegerField(
                blank=True, help_text="Crédits inclus dans le plan Premier", null=True
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="premier_features",
            field=models.TextField(
                blank=True, help_text="Caractéristiques du plan Premier"
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="premier_monthly_cost_mad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coût mensuel Premier en MAD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="pro_credits_per_month",
            field=models.IntegerField(
                blank=True, help_text="Crédits inclus dans le plan Pro", null=True
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="pro_features",
            field=models.TextField(
                blank=True, help_text="Caractéristiques du plan Pro"
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="pro_monthly_cost_mad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coût mensuel Pro en MAD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="standard_credits_per_month",
            field=models.IntegerField(
                blank=True, help_text="Crédits inclus dans le plan Standard", null=True
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="standard_features",
            field=models.TextField(
                blank=True, help_text="Caractéristiques du plan Standard"
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="standard_monthly_cost_mad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coût mensuel Standard en MAD",
                max_digits=10,
                null=True,
            ),
        ),
    ]
