# Generated by Django 5.2.8 on 2025-12-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_address_line1_client_address_line2_and_more"),
        ("projects", "0002_add_indexes"),
        ("subscriptions", "0002_add_pricing_tiers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="creditusage",
            index=models.Index(
                fields=["client"], name="subscriptio_client__feb2d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditusage",
            index=models.Index(
                fields=["subscription"], name="subscriptio_subscri_1112c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditusage",
            index=models.Index(
                fields=["usage_date"], name="subscriptio_usage_d_035fd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditusage",
            index=models.Index(
                fields=["client", "usage_date"], name="subscriptio_client__1d5fdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["billing_month"], name="subscriptio_billing_afca08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["is_active"], name="subscriptio_is_acti_46f9bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["tool", "billing_month"], name="subscriptio_tool_id_cedcaf_idx"
            ),
        ),
    ]
