# Generated by Django 6.0 on 2025-12-14 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("image", "Image Generation"),
                            ("video", "Video Generation"),
                            ("audio", "Audio Generation"),
                            ("both", "Image & Video"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ai_tool",
                    models.CharField(
                        choices=[
                            ("kling_ai", "Kling AI"),
                            ("freepik", "Freepik"),
                            ("openart", "OpenArt"),
                            ("adobe", "Adobe"),
                            ("suno_ai", "Suno AI"),
                            ("grok", "Grok"),
                            ("higgsfield", "Higgsfield"),
                            ("runway", "Runway"),
                        ],
                        max_length=50,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit_name", models.CharField(default="item", max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServicePricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ai_tool", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("image", "Image Generation"),
                            ("video", "Video Generation"),
                            ("audio", "Audio Generation"),
                            ("both", "Image & Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("basic_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "standard_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("premium_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_image",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price_per_video_second",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("features", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Service Pricing",
                "ordering": ["display_name"],
            },
        ),
    ]
