# Generated by Django 5.2.8 on 2025-12-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepricing",
            name="basic_price",
        ),
        migrations.RemoveField(
            model_name="servicepricing",
            name="premium_price",
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="free_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="free_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="premier_credits",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="premier_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="pro_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="pro_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="standard_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="servicepricing",
            name="standard_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
