# Generated by Django 5.2.8 on 2025-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="ice_number",
            field=models.CharField(
                blank=True,
                help_text="Identifiant Commun de l'Entreprise",
                max_length=20,
                null=True,
                verbose_name="ICE",
            ),
        ),
    ]
