# Generated by Django 5.2.8 on 2025-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_address_line1_client_address_line2_and_more"),
        ("invoices", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Acompte en MAD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tva_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Taux TVA en % (0 par défaut)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="title",
            field=models.CharField(
                default="",
                help_text="Titre principal (ex: Campagne ADS)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Non payé"),
                    ("partial", "Partiellement payé"),
                    ("paid", "Payé"),
                    ("overdue", "En retard"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(
                blank=True, help_text="Sous-titre/description", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("bank_transfer", "Virement bancaire"),
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("other", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["payment_status"], name="invoices_in_payment_660c49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="invoices_in_due_dat_6cc0ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client", "payment_status"],
                name="invoices_in_client__829c71_idx",
            ),
        ),
    ]
