# Generated by Django 5.2.8 on 2025-12-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice_deposit_amount_invoice_tva_rate_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="invoices_pa_payment_9bbb9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "payment_date"],
                name="invoices_pa_invoice_bb6c71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method"], name="invoices_pa_payment_21f167_idx"
            ),
        ),
    ]
